force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Release_date__c.field-meta.xml
<CustomField>
    <fullName>Release_date__c</fullName>
    <label>Release date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/utils/MovieBatch.cls
public with sharing class MovieBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Release_date__c, isReleased__c FROM Movie__c]);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Movie__c> movies = new List<Movie__c>();
        for(Movie__c movie : (List<Movie__c>) scope) {
            
            if(movie.Release_date__c <= Date.today()) {
                movie.isReleased__c = true;
                movies.add(movie);
            }
        }
        update movies;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Movie Batch has Finished');
    }
}