force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>MovieActor</label>
    <nameField>
        <label>MovieActor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MoviesActors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>MoviesActors</relationshipLabel>
    <relationshipName>MoviesActors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MoviesActors</relationshipLabel>
    <relationshipName>MoviesActors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MovieActorControllerTest.cls
@isTest
public with sharing class MovieActorControllerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createActors(2, 'Male');
        TestDataFactory.createMovies(1);
    }

    @isTest
    static void shouldCreatedMovieActor() {

        //GIVEN
        List<Movie__c> movies = [SELECT id FROM Movie__c];
        List<Actor__c> actors = [SELECT id FROM Actor__c];
        List<Id> actorIds = new List<Id> ((new Map<Id,Actor__c>(actors)).keySet());

        //WHEN
        Test.startTest();
        MovieActorController.createMovieActor(movies.get(0).Id, actorIds);
        Test.stopTest();

        //THEN
        List<MovieActor__c> actualMovieActors = [SELECT Id FROM MovieActor__c];

        System.assertEquals(2,actualMovieActors.size(), 'Unexpected Result');


    }
}