force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Release_date__c.field-meta.xml
<CustomField>
    <fullName>Release_date__c</fullName>
    <label>Release date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>MovieActor</label>
    <nameField>
        <label>MovieActor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MoviesActors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MovieActor__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>MoviesActors</relationshipLabel>
    <relationshipName>MoviesActors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MovieActor__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MoviesActors</relationshipLabel>
    <relationshipName>MoviesActors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/utils/TestDataFactory.cls
@IsTest
public class TestDataFactory {
   public static List<Movie__c> createMovies(Integer numberOfMovies, Date releaseDate) {
        List<Movie__c> movies = new List<Movie__c>();
        for (Integer i = 0; i < numberOfMovies; i++) {
            movies.add(
                new Movie__c(Name = 'Movie' + i, Category__c = 'Action', Release_date__c = releaseDate)
        );
    }
   
        insert movies;
        return movies;
    }

    public static List<Actor__c> createActors(Integer numberOfMovies, String gender) {
       
        List<Actor__c> actors = new List<Actor__c>();
        for (Integer i = 0; i < numberOfMovies; i++) {
            actors.add(
                new Actor__c(Name = 'Actor' + i, Gender__c = gender)
            );
        }
       
        insert actors;
        return actors;
    }

    public static List<MovieActor__c> createMovieActor(List<Id> movieIds, List<Id> actorsIds) {
       
        List<MovieActor__c> moviesActors = new List<MovieActor__c> {
            new MovieActor__c(Movie__c = movieIds.get(0), Actor__c = actorsIds.get(0)),
            new MovieActor__c(Movie__c = movieIds.get(0), Actor__c = actorsIds.get(1)),
            new MovieActor__c(Movie__c = movieIds.get(1), Actor__c = actorsIds.get(1))
          };
       
        insert moviesActors;
        return moviesActors;
    }
}